cache: 
  directories:
    - docker_images
  
language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - docker load -i docker_images/images.tar || true

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
  
install:
  - pip install -r devcontainer/build/host/requirements.txt

script:
  - pylint backend/ --exit-zero
  
after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
