"""empty message

Revision ID: 524c5165f52a
Revises: 
Create Date: 2020-02-12 10:15:34.413642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '524c5165f52a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('book_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=32), nullable=False),
    sa.Column('preface', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
