"""empty message

Revision ID: 8678a2b8bb06
Revises: e0a523e5699b
Create Date: 2020-02-12 17:14:56.658079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8678a2b8bb06'
down_revision = 'e0a523e5699b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
