"""empty message

Revision ID: f614744d7a6a
Revises: 524c5165f52a
Create Date: 2020-02-12 12:33:08.905023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f614744d7a6a'
down_revision = '524c5165f52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'updated_at')
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###
