version: '3.3'
services:
  hjwzw_redis:
    image: redis:5.0.5-buster
    container_name: hjwzw_redis
    restart: on-failure:5
    command: "redis-server --requirepass RedisNyv775 --appendonly yes"
    networks:
      - hjwzw-net
    volumes:
      - hjwzw_redis-volume:/data

  hjwzw_postgres:
    image: postgres:11.5-alpine
    container_name: hjwzw_postgres
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD: "PostNyv775"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "hjwzw"
    ports:
      - "5432:5432"
    networks:
      - hjwzw-net
    volumes:
      - hjwzw_postgres-volume:/var/lib/postgresql/data
    
  hjwzw_host:
    build:
      context: ./
      dockerfile: ./build/host/Dockerfile
    container_name: hjwzw_host
    user: sung
    tty:
      true
    depends_on:
      - hjwzw_redis
      - hjwzw_postgres
    networks:
      - hjwzw-net

networks:
  hjwzw-net:
    external: true

volumes:
  hjwzw_postgres-volume:
    external: true
  hjwzw_redis-volume:
    external: true
